# Generated by Django 5.0.2 on 2024-08-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_info',
            name='Profile_Picture',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
    ]
