# Generated by Django 5.0.2 on 2024-08-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_rename_register_info_registerinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerinfo',
            old_name='Address',
            new_name='Address_Line1',
        ),
        migrations.RemoveField(
            model_name='registerinfo',
            name='Line1',
        ),
    ]
