# Generated by Django 5.0.2 on 2024-08-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_register_info_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register_info',
            new_name='Registerinfo',
        ),
    ]
