# Generated by Django 5.0.2 on 2024-08-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_rename_address_registerinfo_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerinfo',
            name='Confirm_Password',
        ),
    ]
