# Generated by Django 5.0.2 on 2024-08-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_remove_registerinfo_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerinfo',
            name='Profile_Picture',
            field=models.ImageField(default='', max_length=350, upload_to='images'),
        ),
    ]
