# Generated by Django 5.0.2 on 2024-08-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_alter_registerinfo_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerinfo',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
